import { createHash } from 'node:crypto';
import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { lstat, mkdir, rm, stat, utimes, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { FastifyBaseLogger } from 'fastify';
import {
	ETV_CONTRACT_REVISION,
	toEtvChannelConfig,
	type EtvCompatibleChannel,
} from '@moirai/ersatztv-contract';
import type {
	Channel,
	ChannelSessionStatus,
	PlaybackSessionAcceleration,
	PlaybackEngineStatus,
	PlaybackNowPlayingStatus,
	PlaybackSettings,
} from '@moirai/shared';
import type {
	HardwareAccelerationPrediction,
	HardwareAccelerationPredictionRequest,
} from '@moirai/shared/api-contracts';
import type { LiveEventPublisher } from '../operations/live-events.js';
import type { PlayoutSynchronizer } from './playout-synchronizer.js';
import type { Repository } from '../repository/index.js';
import type { MaterializedSegmentRecord } from '../repository/contracts.js';
import type { ResourcePressureCoordinator } from '../operations/resource-pressure.js';
import { currentTimestamp } from '../time.js';
import type { HardwareAccelerationResolver } from './hardware-acceleration.js';
import {
	accelerationFromWorkerLine,
	PlaybackClientTracker,
	type PlaybackClientObservation,
} from './session-observability.js';
import { ViewingPreferenceObserver } from './viewing-preference-observer.js';

/** Session filenames generated by the pinned channel worker and safe to expose. */
const SESSION_FILE = /^(?:live(?:_sub)?\.m3u8|live\d{6}\.(?:ts|vtt))$/;
/** Maximum child-output chunk recorded as one structured log message. */
const MAX_LOG_CHUNK = 16 * 1024;

/** Signal that the configured playback engine cannot start channels. */
export class PlaybackUnavailableError extends Error {
	readonly statusCode = 503;

	constructor(message = 'Playback engine is unavailable') {
		super(message);
		this.name = 'PlaybackUnavailableError';
	}
}

/** Signal that every configured playback slot is currently occupied. */
export class PlaybackCapacityError extends Error {
	readonly statusCode = 503;

	constructor() {
		super('Playback capacity is currently full');
		this.name = 'PlaybackCapacityError';
	}
}

/** Runtime state owned for one child process. */
interface ActiveSession {
	channel: Channel;
	child: ChildProcessWithoutNullStreams;
	clients: PlaybackClientTracker;
	acceleration: PlaybackSessionAcceleration;
	stderrLineBuffer: string;
	configDigest: string;
	startedAt: string;
	state: 'starting' | 'ready' | 'stale' | 'stopping';
	ready: Promise<void>;
	resolveReady: () => void;
	rejectReady: (error: Error) => void;
}

/** Last failed start retained for operator diagnostics. */
interface FailedSession {
	channel: Channel;
	startedAt: string;
	error: string;
	acceleration: PlaybackSessionAcceleration;
}

/** Describe an authored acceleration before an Automatic worker pipeline has been observed. */
function pendingAcceleration(channel: Channel): PlaybackSessionAcceleration {
	return channel.video.accel === 'automatic'
		? 'pending'
		: channel.video.accel ?? 'none';
}

/** Reduce one committed current segment to the safe fields required by playback status. */
function nowPlayingStatus(
	record: MaterializedSegmentRecord | undefined,
): PlaybackNowPlayingStatus | null {
	if (!record) {
		return null;
	}

	return {
		title: record.segment.title,
		artworkUrl: record.mediaSnapshot?.artworkUrl ?? null,
		startedAt: record.segment.start,
		finishesAt: record.segment.finish,
	};
}

/**
 * Own on-demand ErsatzTV channel workers and their private HLS output. The engine enforces persisted
 * playback capacity, coalesces channel startup, bounds process shutdown, and exposes safe stream URLs
 * and failure state to clients.
 */
export class PlaybackEngine {
	private readonly sessions = new Map<string, ActiveSession>();
	private readonly starts = new Map<string, Promise<void>>();
	private readonly reservations = new Set<string>();
	private readonly failures = new Map<string, FailedSession>();
	private engineVersion: string | null = null;
	private engineError: string | null = 'Playback engine has not been checked';
	private running = false;
	private viewingPreferences: ViewingPreferenceObserver | null = null;

	constructor(
		private readonly repository: Repository,
		private readonly playout: PlayoutSynchronizer,
		private readonly events: LiveEventPublisher,
		private readonly logger: FastifyBaseLogger,
		private readonly hardwareAcceleration: HardwareAccelerationResolver,
		private readonly enginePath: string,
		private readonly streamRoot: string,
		private readonly publicUrl: string,
		private readonly readyTimeoutMs: number,
		private readonly stopGraceMs: number,
		private readonly resourcePressure?: ResourcePressureCoordinator,
	) {}

	/** Probe the configured binary without preventing the management UI from starting. */
	async start(): Promise<void> {
		this.running = true;
		const settings = await this.repository.getPlaybackSettings();
		this.viewingPreferences = new ViewingPreferenceObserver(
			this.repository,
			this.logger,
			settings.viewingPreferencesEnabled,
		);
		await mkdir(this.streamRoot, { recursive: true });
		try {
			this.engineVersion = await this.probeVersion();
			this.engineError = null;
		}
		catch (error) {
			this.engineError = 'Playback engine executable is unavailable';
			this.logger.warn({ error }, 'Playback engine probe failed');
		}
	}

	/** Stop every active worker within the configured bounded grace period. */
	async close(): Promise<void> {
		this.running = false;
		await Promise.allSettled([...this.sessions.keys()].map((channelId) => this.stop(channelId)));
		await Promise.allSettled(this.starts.values());
		await Promise.allSettled([...this.sessions.keys()].map((channelId) => this.stop(channelId)));
	}

	/** Return lightweight process-level playback readiness. */
	health(): { status: 'ready' | 'degraded'; detail?: string } {
		if (!this.running) {
			return { status: 'degraded', detail: 'Playback engine manager is not running' };
		}

		return this.engineError
			? { status: 'degraded', detail: this.engineError }
			: { status: 'ready' };
	}

	/** Return engine capability, URLs, capacity, and channel session state. */
	async status(): Promise<PlaybackEngineStatus> {
		// Load capacity, channel labels, and current committed programming in bounded queries.
		const statusAt = currentTimestamp();
		const statusRangeEnd = new Date(Date.parse(statusAt) + 1).toISOString();
		const currentProgramming = this.sessions.size > 0
			? this.repository.listMaterializedTimelineSegments(statusAt, statusRangeEnd)
			: Promise.resolve([]);
		const [settings, channels, currentSegments] = await Promise.all([
			this.repository.getPlaybackSettings(),
			this.repository.listChannels(),
			currentProgramming,
		]);
		const channelsById = new Map(channels.map((channel) => [channel.id, channel]));
		const activeChannelIds = new Set(this.sessions.keys());
		const currentSegmentsByChannel = new Map(
			currentSegments
				.filter((record) => activeChannelIds.has(record.segment.channelId))
				.map((record) => [record.segment.channelId, record]),
		);
		const sessions: ChannelSessionStatus[] = [...this.sessions.values()].map((session) => {
			const channel = channelsById.get(session.channel.id) ?? session.channel;
			return {
				channelId: channel.id,
				channelNumber: channel.number,
				channelName: channel.name,
				state: session.state,
				startedAt: session.startedAt,
				pid: session.child.pid ?? null,
				lastError: null,
				acceleration: session.acceleration,
				nowPlaying: nowPlayingStatus(currentSegmentsByChannel.get(channel.id)),
				clients: session.clients.active(),
			};
		});

		// Include worker-launch failures that have no active child process.
		for (const failed of this.failures.values()) {
			if (this.sessions.has(failed.channel.id)) {
				continue;
			}

			const channel = channelsById.get(failed.channel.id) ?? failed.channel;
			sessions.push({
				channelId: channel.id,
				channelNumber: channel.number,
				channelName: channel.name,
				state: 'failed',
				startedAt: failed.startedAt,
				pid: null,
				lastError: failed.error,
				acceleration: failed.acceleration,
				nowPlaying: null,
				clients: [],
			});
		}

		// Include playout-generation failures that prevented a worker launch.
		for (const [channelId, failed] of this.playout.channelFailures()) {
			if (this.sessions.has(channelId) || this.failures.has(channelId)) {
				continue;
			}

			const channel = channelsById.get(channelId);
			if (!channel) {
				continue;
			}

			sessions.push({
				channelId,
				channelNumber: channel.number,
				channelName: channel.name,
				state: 'failed',
				startedAt: failed.failedAt,
				pid: null,
				lastError: failed.message,
				acceleration: pendingAcceleration(channel),
				nowPlaying: null,
				clients: [],
			});
		}

		// Return stable channel ordering and aggregate engine health.
		sessions.sort((left, right) => left.channelNumber.localeCompare(right.channelNumber, undefined, {
			numeric: true,
			sensitivity: 'base',
		}));
		const playoutHealth = this.playout.health();
		const detail = this.engineError ?? playoutHealth.detail ?? null;
		return {
			status: detail ? 'degraded' : 'ready',
			engineVersion: this.engineVersion,
			contractRevision: ETV_CONTRACT_REVISION,
			maxActiveSessions: settings.maxActiveSessions,
			activeSessionCount: this.sessions.size,
			sessions,
			detail,
			m3uUrl: `${this.publicUrl}/iptv/channels.m3u`,
			epgUrl: `${this.publicUrl}/epg.xml`,
		};
	}

	/** Persist a new capacity limit and notify connected status views. */
	async updateSettings(settings: PlaybackSettings): Promise<PlaybackSettings> {
		const saved = await this.repository.setPlaybackSettings(settings);
		this.viewingPreferences?.setEnabled(saved.viewingPreferencesEnabled);
		this.events.publish({
			type: 'playback.changed',
			data: { channelId: null, reason: 'settings-changed' },
		});
		return saved;
	}

	/** Predict the concrete backend that Automatic would use for an unsaved channel target. */
	async predictHardwareAcceleration(
		request: HardwareAccelerationPredictionRequest,
	): Promise<HardwareAccelerationPrediction> {
		const { outcome, accel, detail } = await this.hardwareAcceleration.resolve(request);
		return { outcome, accel, detail };
	}

	/** Start or reuse one channel worker, waiting until its HLS output is ready. */
	async ensureSession(channel: Channel, client?: PlaybackClientObservation): Promise<void> {
		const current = this.sessions.get(channel.id);
		if (current) {
			if (client) {
				this.observeClient(current, client);
			}
			if (current.state === 'stopping') {
				throw new PlaybackUnavailableError('Channel stream is restarting');
			}

			await current.ready;
			return;
		}

		const pending = this.starts.get(channel.id);
		if (pending) {
			await pending;
			const started = this.sessions.get(channel.id);
			if (client && started) {
				this.observeClient(started, client);
			}
			return;
		}

		const operation = this.startSession(channel, client);
		this.starts.set(channel.id, operation);
		try {
			await operation;
		}
		catch (error) {
			if (!(error instanceof PlaybackCapacityError) && !this.failures.has(channel.id)) {
				const message = error instanceof PlaybackUnavailableError
					? error.message
					: this.playout.channelFailure(channel.id) ?? 'Channel playback could not start';
				this.failures.set(channel.id, {
					channel,
					startedAt: currentTimestamp(),
					error: message,
					acceleration: pendingAcceleration(channel),
				});
				this.events.publish({
					type: 'playback.changed',
					data: { channelId: channel.id, reason: 'failed' },
				});
			}
			throw error;
		}
		finally {
			if (this.starts.get(channel.id) === operation) {
				this.starts.delete(channel.id);
			}
		}
	}

	/** Reserve capacity and launch one worker after its playout is current. */
	private async startSession(channel: Channel, client?: PlaybackClientObservation): Promise<void> {
		if (this.engineError) {
			throw new PlaybackUnavailableError();
		}

		const settings = await this.repository.getPlaybackSettings();
		if (this.sessions.size + this.reservations.size >= settings.maxActiveSessions) {
			throw new PlaybackCapacityError();
		}

		this.reservations.add(channel.id);
		try {
			await this.playout.syncChannel(channel.id);
			if (!this.running) {
				throw new PlaybackUnavailableError('Playback engine is stopping');
			}

			await this.launchSession(channel, client);
		}
		finally {
			this.reservations.delete(channel.id);
		}
	}

	/** Spawn one configured worker and wait for its readiness marker. */
	private async launchSession(channel: Channel, client?: PlaybackClientObservation): Promise<void> {
		const playoutFolder = this.playout.channelFolder(channel.id);
		const effectiveChannel = await this.effectiveChannel(channel, true);
		const document = toEtvChannelConfig(effectiveChannel, playoutFolder);
		const config = `${JSON.stringify(document)}\n`;
		const outputFolder = this.outputFolder(channel.id);
		await rm(outputFolder, { recursive: true, force: true });
		await mkdir(outputFolder, { recursive: true });
		if (!this.running) {
			throw new PlaybackUnavailableError('Playback engine is stopping');
		}

		let resolveReady = (): void => undefined;
		let rejectReady: (error: Error) => void = () => undefined;
		const ready = new Promise<void>((resolve, reject) => {
			resolveReady = resolve;
			rejectReady = reject;
		});
		const child = await this.spawnEngine(
			['run', '--output-folder', outputFolder, '--number', channel.number, '-'],
			process.platform !== 'win32',
		);
		const session: ActiveSession = {
			channel,
			child,
			clients: new PlaybackClientTracker(),
			acceleration: 'pending',
			stderrLineBuffer: '',
			configDigest: this.configDigest(channel, config),
			startedAt: currentTimestamp(),
			state: 'starting',
			ready,
			resolveReady,
			rejectReady,
		};
		if (client) {
			this.observeClient(session, client);
		}
		this.sessions.set(channel.id, session);
		this.failures.delete(channel.id);
		this.logChildOutput(session);
		this.observeExit(session);
		child.stdin.end(config);
		this.events.publish({ type: 'playback.changed', data: { channelId: channel.id, reason: 'started' } });
		void this.waitUntilReady(session);
		await ready;
	}

	/** Mark an active session stale when its effective runtime configuration changes. */
	async handleChannelChange(channelId: string, deleted = false): Promise<void> {
		const session = this.sessions.get(channelId);
		if (!session) {
			return;
		}

		if (deleted) {
			await this.stop(channelId);
			await rm(this.outputFolder(channelId), { recursive: true, force: true });
			return;
		}

		const channel = await this.repository.getChannel(channelId);
		if (!channel) {
			await this.stop(channelId);
			return;
		}

		const effectiveChannel = await this.effectiveChannel(channel);
		const document = toEtvChannelConfig(effectiveChannel, this.playout.channelFolder(channel.id));
		const config = `${JSON.stringify(document)}\n`;
		if (session.configDigest !== this.configDigest(channel, config)) {
			session.state = 'stale';
			this.events.publish({ type: 'playback.changed', data: { channelId, reason: 'stale' } });
		}
	}

	/** Restart one channel immediately, including a previously failed inactive session. */
	async restart(channelId: string): Promise<void> {
		const channel = await this.repository.getChannel(channelId);
		if (!channel) {
			throw new Error('Channel not found');
		}

		await this.stop(channelId);
		this.failures.delete(channelId);
		await this.ensureSession(channel);
	}

	/** Move affected channels to inherited playout before a fallback override is deleted. */
	async transitionFallbackRemoval(channelId: string | null): Promise<void> {
		const channelIds = channelId
			? [channelId]
			: (await this.repository.listChannels()).map((channel) => channel.id);
		const active = new Set(channelIds.filter((id) => this.sessions.has(id)));
		for (const activeChannelId of active) {
			await this.stop(activeChannelId);
		}
		for (const affectedChannelId of channelIds) {
			try {
				if (active.has(affectedChannelId)) {
					await this.restart(affectedChannelId);
				}
				else {
					await this.playout.syncChannel(affectedChannelId);
				}
			}
			catch (error) {
				this.logger.warn({ error, channelId: affectedChannelId }, 'Fallback playback update failed');
			}
		}
	}

	/** Swap a fallback while affected workers are stopped and recover failures through later syncs. */
	async transitionFallbackReplacement(
		channelId: string | null,
		activate: () => Promise<void>,
	): Promise<void> {
		const channelIds = channelId
			? [channelId]
			: (await this.repository.listChannels()).map((channel) => channel.id);
		const active = new Set(channelIds.filter((id) => this.sessions.has(id)));
		for (const activeChannelId of active) {
			await this.stop(activeChannelId);
		}
		await activate();
		for (const affectedChannelId of channelIds) {
			try {
				if (active.has(affectedChannelId)) {
					await this.restart(affectedChannelId);
				}
				else {
					await this.playout.syncChannel(affectedChannelId);
				}
			}
			catch (error) {
				this.logger.warn({ error, channelId: affectedChannelId }, 'Fallback playback update failed');
			}
		}
	}

	/** Replace Moirai's Automatic choice with worker-compatible runtime configuration. */
	private async effectiveChannel(
		channel: Channel,
		logDecision = false,
	): Promise<EtvCompatibleChannel> {
		if (channel.video.accel !== 'automatic') {
			return {
				...channel,
				video: { ...channel.video, accel: channel.video.accel },
			};
		}

		const resolution = await this.hardwareAcceleration.resolve({
			format: channel.video.format,
			bitDepth: channel.video.bitDepth,
			width: channel.video.width,
			height: channel.video.height,
			vaapiDevice: channel.video.vaapiDevice,
			vaapiDriver: channel.video.vaapiDriver,
			ffmpegPath: channel.ffmpegPath,
		});
		if (logDecision) {
			this.logger.info({
				channelId: channel.id,
				channelNumber: channel.number,
				accel: resolution.accel,
				outcome: resolution.outcome,
				detail: resolution.detail,
			}, 'Resolved automatic channel hardware acceleration');
		}

		return {
			...channel,
			video: {
				...channel.video,
				accel: resolution.accel,
				vaapiDevice: resolution.vaapiDevice ?? channel.video.vaapiDevice,
				vaapiDriver: resolution.vaapiDriver ?? channel.video.vaapiDriver,
			},
		};
	}

	/** Return a validated generated file path and keep the worker alive. */
	async sessionFile(
		channelId: string,
		filename: string,
		client?: PlaybackClientObservation,
	): Promise<string> {
		if (!SESSION_FILE.test(filename)) {
			throw new Error('Session file not found');
		}

		const session = this.sessions.get(channelId);
		if (!session || session.state === 'stopping') {
			throw new Error('Session file not found');
		}
		if (client) {
			this.observeClient(session, client);
		}

		await session.ready;
		await this.touchHeartbeat(channelId);
		const file = path.join(this.outputFolder(channelId), filename);
		const details = await lstat(file);
		if (!details.isFile()) {
			throw new Error('Session file not found');
		}

		return file;
	}

	/** Record client activity for status and anonymous viewing-preference qualification. */
	private observeClient(session: ActiveSession, client: PlaybackClientObservation): void {
		const activity = session.clients.observe(client);
		this.viewingPreferences?.observe(session.channel.id, activity);
	}

	/** Stop one child and escalate after its graceful deadline. */
	private async stop(channelId: string): Promise<void> {
		const session = this.sessions.get(channelId);
		if (!session) {
			return;
		}

		session.state = 'stopping';
		session.rejectReady(new PlaybackUnavailableError('Channel stream stopped before becoming ready'));
		this.signal(session, 'SIGTERM');
		await Promise.race([
			new Promise<void>((resolve) => session.child.once('exit', () => resolve())),
			new Promise<void>((resolve) => setTimeout(resolve, this.stopGraceMs)),
		]);
		if (this.sessions.get(channelId) === session) {
			this.signal(session, 'SIGKILL');
		}
	}

	/** Send a signal to the whole Unix process group or the direct child elsewhere. */
	private signal(session: ActiveSession, signal: NodeJS.Signals): void {
		try {
			if (process.platform !== 'win32' && session.child.pid) {
				process.kill(-session.child.pid, signal);
			}
			else {
				session.child.kill(signal);
			}
		}
		catch {
			// The process may have exited between the state check and signal delivery.
		}
	}

	/** Wait for the worker readiness marker while also observing process exit. */
	private async waitUntilReady(session: ActiveSession): Promise<void> {
		const deadline = Date.now() + this.readyTimeoutMs;
		const marker = path.join(this.outputFolder(session.channel.id), '.ready');
		while (this.sessions.get(session.channel.id) === session && Date.now() < deadline) {
			try {
				if ((await stat(marker)).isFile()) {
					session.state = 'ready';
					await this.touchHeartbeat(session.channel.id);
					session.resolveReady();
					this.events.publish({
						type: 'playback.changed',
						data: { channelId: session.channel.id, reason: 'ready' },
					});
					return;
				}
			}
			catch {
				// The worker creates the marker only after enough HLS segments exist.
			}
			await new Promise((resolve) => setTimeout(resolve, 100));
		}
		if (this.sessions.get(session.channel.id) !== session) {
			return;
		}

		const error = new PlaybackUnavailableError('Channel stream did not become ready in time');
		session.rejectReady(error);
		this.failures.set(session.channel.id, {
			channel: session.channel,
			startedAt: session.startedAt,
			error: error.message,
			acceleration: session.acceleration,
		});
		await this.stop(session.channel.id);
	}

	/** Observe child completion and clear its session ownership exactly once. */
	private observeExit(session: ActiveSession): void {
		session.child.once('error', (error) => {
			if (this.sessions.get(session.channel.id) !== session) {
				return;
			}

			this.sessions.delete(session.channel.id);
			this.logger.error({ error, channelId: session.channel.id }, 'Playback worker failed to start');
			const failure = new PlaybackUnavailableError('Playback worker could not be started');
			session.rejectReady(failure);
			this.failures.set(session.channel.id, {
				channel: session.channel,
				startedAt: session.startedAt,
				error: failure.message,
				acceleration: session.acceleration,
			});
			this.events.publish({
				type: 'playback.changed',
				data: { channelId: session.channel.id, reason: 'failed' },
			});
		});
		session.child.once('exit', (code, signal) => {
			if (this.sessions.get(session.channel.id) !== session) {
				return;
			}

			this.sessions.delete(session.channel.id);
			const expected = session.state === 'stopping' || (code === 0 && session.state !== 'starting');
			if (!expected) {
				const message = `Playback worker exited (${signal ?? code ?? 'unknown'})`;
				session.rejectReady(new PlaybackUnavailableError(message));
				this.failures.set(session.channel.id, {
					channel: session.channel,
					startedAt: session.startedAt,
					error: message,
					acceleration: session.acceleration,
				});
				this.events.publish({
					type: 'playback.changed',
					data: { channelId: session.channel.id, reason: 'failed' },
				});
			}
			else {
				this.events.publish({
					type: 'playback.changed',
					data: { channelId: session.channel.id, reason: 'stopped' },
				});
			}
		});
	}

	/** Forward bounded child output through Moirai's structured logger. */
	private logChildOutput(session: ActiveSession): void {
		const log = (stream: 'stdout' | 'stderr', chunk: Buffer): void => {
			const output = chunk.toString('utf8', 0, MAX_LOG_CHUNK);
			if (stream === 'stderr') {
				this.observeWorkerDiagnostics(session, output);
			}

			const message = output.trim();
			if (message) {
				this.logger.info(
					{ channelId: session.channel.id, channelNumber: session.channel.number, stream },
					message,
				);
			}
		};
		session.child.stdout.on('data', (chunk: Buffer) => log('stdout', chunk));
		session.child.stderr.on('data', (chunk: Buffer) => log('stderr', chunk));
		session.child.stdin.on('error', (error) => {
			this.logger.debug({ error, channelId: session.channel.id }, 'Playback worker input closed');
		});
	}

	/** Derive actual item encoder acceleration from complete worker diagnostic lines. */
	private observeWorkerDiagnostics(session: ActiveSession, output: string): void {
		const lines = `${session.stderrLineBuffer}${output}`.split(/\r?\n/u);
		session.stderrLineBuffer = (lines.pop() ?? '').slice(-MAX_LOG_CHUNK);
		for (const line of lines) {
			const acceleration = accelerationFromWorkerLine(line);
			if (acceleration && acceleration !== session.acceleration) {
				session.acceleration = acceleration;
				this.logger.info({
					channelId: session.channel.id,
					channelNumber: session.channel.number,
					acceleration,
				}, 'Observed playback pipeline acceleration');
			}
		}
	}

	/** Touch the worker heartbeat without following a user-controlled path. */
	private async touchHeartbeat(channelId: string): Promise<void> {
		const heartbeat = path.join(this.outputFolder(channelId), '.heartbeat');
		const now = new Date();
		try {
			await utimes(heartbeat, now, now);
		}
		catch {
			await writeFile(heartbeat, '');
		}
	}

	/** Return one stable private output directory. */
	private outputFolder(channelId: string): string {
		return path.join(this.streamRoot, channelId);
	}

	/** Hash every value fixed for the lifetime of one worker. */
	private configDigest(channel: Channel, config: string): string {
		return createHash('sha256').update(channel.number).update('\0').update(config).digest('hex');
	}

	/** Execute the lightweight version command with bounded output and time. */
	private probeVersion(): Promise<string> {
		const operation = () => this.probeVersionOnce();
		return this.resourcePressure
			? this.resourcePressure.runEssential('playback engine version check', operation)
			: operation();
	}

	/** Execute one playback-engine version process without applying pressure retries. */
	private probeVersionOnce(): Promise<string> {
		return new Promise((resolve, reject) => {
			const child = spawn(this.enginePath, ['--version'], { stdio: ['ignore', 'pipe', 'pipe'] });
			let output = '';
			const timer = setTimeout(() => {
				child.kill('SIGKILL');
				reject(new Error('Playback engine version check timed out'));
			}, 5_000);
			child.stdout.on('data', (chunk: Buffer) => {
				output += chunk.toString('utf8', 0, Math.max(0, 4_096 - output.length));
			});
			child.stderr.on('data', (chunk: Buffer) => {
				output += chunk.toString('utf8', 0, Math.max(0, 4_096 - output.length));
			});
			child.once('error', (error) => {
				clearTimeout(timer);
				reject(new Error('Unable to execute playback engine', { cause: error }));
			});
			child.once('exit', (code) => {
				clearTimeout(timer);
				if (code === 0) {
					resolve(output.trim() || 'unknown');
				}
				else {
					reject(new Error('Playback engine version check failed'));
				}
			});
		});
	}

	/** Spawn a channel worker and confirm that the OS accepted the process launch. */
	private spawnEngine(args: string[], detached: boolean): Promise<ChildProcessWithoutNullStreams> {
		const operation = () => new Promise<ChildProcessWithoutNullStreams>((resolve, reject) => {
			const child = spawn(this.enginePath, args, {
				detached,
				stdio: ['pipe', 'pipe', 'pipe'],
			});
			const failed = (error: Error): void => {
				child.removeListener('spawn', started);
				reject(error);
			};
			const started = (): void => {
				child.removeListener('error', failed);
				resolve(child);
			};
			child.once('error', failed);
			child.once('spawn', started);
		});
		return this.resourcePressure
			? this.resourcePressure.runEssential('channel playback process launch', operation)
			: operation();
	}
}
